### ISSUE TITLE
Fix clients IPs by trusting the proxy

### ISSUE THREAD

**Issue by Petitoto** [aeecleclair/Hyperion#292]
### Subject of the issue

We should add a settings to trust X-Forwarded-For header for a specifc proxy. Thus, we would get the real IP addresses of the clients instead of the IP of the proxy.

### Your environment

- Version of Hyperion : latest release
- Operating system : debian

### Steps to reproduce

Run the server behind a proxy and let clients connect to Hyperion.

### Expected behaviour

We should see the clients' IP in the logs.

### Actual behaviour

We see the proxy IP address in the logs.

**Comment by julien4215** [comment]
Solved on server side
