### ISSUE TITLE
Specific CalendarEventType causes internal server error

### ISSUE THREAD

**Issue by guillaumetavernier** [aeecleclair/Hyperion#346]
### Subject of the issue

While using Hyperion in production, trying to create an event with `Asso indé` type create an error on backend.
This error does not occur when self-hosting Hyperion under a Windows OS.

```
hyperion-1-app    | [parameters: (title', 'aut', datetime.datetime(2024, 2, 19, 1, 0, tzinfo=<DstTzInfo 'Europe/Paris' CET+1:00:00 STD>), datetime.datetime(2024, 2, 22, 0, 59, tzinfo=<DstTzInfo 'Europe/Paris' CET+1:00:00 STD>), True, 'Hall du M16', 'independentAssociation', 'hvv', '', 'id')]
hyperion-1-app    | (Background on this error at: https://sqlalche.me/e/20/dbapi)
hyperion-1-app    | 23-Feb-24 09:52:29 - uvicorn.error - ERROR - Exception in ASGI application
```

### Your environment

- Production or Preproduction

### Steps to reproduce

- Create or edit an event with "Asso Indé" type

**Comment by Petitoto** [comment]
Error is `invalid input value for enum calendareventtype: "independentAssociation"`

The issue is raised only on preproduction servers (everything works in production). A migration may have failed in the past.
